### ISSUE TITLE
Header are not sent if there are no params

### ISSUE THREAD

**Issue by peck** [oarrabi/exrequester#2]
Cannot make "index" requests with headers

```
defmodule Api do
use EXRequester
  @headers [
    "Content-Type": "application/json",
    "Accept": "application/json",
    "x-user-token": "a892079d-8028-46ec-8208-225e1a0e3af5",
    "x-user-email": "demo@example.com",
  ]
  @get "/posts"
  defreq get_posts
end
```

when calling 

```
Api.get_posts()
```

headers are not populated

**Comment by nsomar** [comment]
Hello @peck 
Thanks for contacting me, I just solved this issue
Please update to version 0.5.2

Please let me know if this solve the issue.

**Comment by peck** [comment]
Seems to work great, I was going to work on a PR for you this weekend but you beat me to it. Thanks!

**Comment by nsomar** [comment]
Hello for defining a global set of headers check issue #3 
I would love a hand into extending and adding more features to exrequester. Like the ability to handle auth, maybe even having an auth1/2 or basic auth. 

As for this issue, I will be closing it as its a confirmed fix.
